export const Users = [
    {
        "id":1,
        "name": "Yash Sahu",
        "username":"yash",
        "email":"yash123@gmail.com",
        "phone":57174544431,
        "website":"yash.com",
    },
    {
        "id":2,
        "name": "Yash Sahu",
        "username":"yash",
        "email":"yash123@gmail.com",
        "phone":57174544431,
        "website":"yash.com",
    },
    {
        "id":3,
        "name": "Yash Sahu",
        "username":"yash",
        "email":"yash123@gmail.com",
        "phone":57174544431,
        "website":"yash.com",
    },
    {
        "id":4,
        "name": "Yash Sahu",
        "username":"yash",
        "email":"yash123@gmail.com",
        "phone":57174544431,
        "website":"yash.com",
    },
    {
        "id":5,
        "name": "Yash Sahu",
        "username":"yash",
        "email":"yash123@gmail.com",
        "phone":57174544431,
        "website":"yash.com",
    },
]