export const Users = [
    {
        "id":1,
        "name": "Leanne Graham",
        "username":"Bret",
        "email":"Sincere@april.biz",
        "phone":"1-770-736-8031",
        "website":"hildegard.org",
    },
    {
        "id":2,
        "name": "Ervin Howell",
        "username":"Antonette",
        "email":"Shanna@melissa.tv",
        "phone":"100-692-6593",
        "website":"yash.com",
    },
    {
        "id":3,
        "name": "Clementine Bauch",
        "username":"Samantha",
        "email":"Nathan@yesenia.net",
        "phone":"1-463-123-4447",
        "website":"ramiro.info",
    },
    {
        "id":4,
        "name": "Patricia Lebsack",
        "username":"Karianne",
        "email":"Julianne.OConner@kory.org",
        "phone":"493-170-9623",
        "website":"kale.biz",
    },
    {
        "id":5,
        "name": "Yash Sahu",
        "username":"yash",
        "email":"yash123@gmail.com",
        "phone":"57174544431",
        "website":"yash.com",
    },
]